# Generated by Django 3.2 on 2022-04-13 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceperMin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cost', models.CharField(max_length=8)),
                ('Cost_per_min', models.IntegerField()),
                ('after_3min', models.IntegerField()),
                ('after_10min', models.IntegerField()),
            ],
        ),
    ]
