# Generated by Django 3.2 on 2022-04-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_pricepermin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('yy', models.IntegerField(primary_key=True, serialize=False)),
                ('ac_case', models.IntegerField()),
                ('dead', models.IntegerField()),
                ('injured', models.IntegerField()),
            ],
            options={
                'db_table': 'accident',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AccType',
            fields=[
                ('ac_type', models.CharField(max_length=20)),
                ('ac_detail', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('ac_case', models.IntegerField()),
                ('ac_per', models.IntegerField()),
            ],
            options={
                'db_table': 'acc_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Costs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('cost', models.IntegerField()),
                ('cpm', models.IntegerField()),
                ('cost_0min', models.IntegerField()),
                ('cost_5min', models.IntegerField()),
                ('cost_10min', models.IntegerField()),
                ('cost_15min', models.IntegerField()),
                ('cost_20min', models.IntegerField()),
                ('cost_25min', models.IntegerField()),
                ('cost_30min', models.IntegerField()),
            ],
            options={
                'db_table': 'Costs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CostsTop5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('cost', models.IntegerField()),
                ('cpm', models.IntegerField()),
                ('cost_0min', models.IntegerField()),
                ('cost_5min', models.IntegerField()),
                ('cost_10min', models.IntegerField()),
                ('cost_15min', models.IntegerField()),
                ('cost_20min', models.IntegerField()),
                ('cost_25min', models.IntegerField()),
                ('cost_30min', models.IntegerField()),
            ],
            options={
                'db_table': 'Costs_top5',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SafetyRule',
            fields=[
                ('rule', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('follow_rule_case', models.IntegerField(blank=True, null=True)),
                ('follow_rule_per', models.IntegerField(blank=True, null=True)),
                ('not_follow_rule_case', models.IntegerField(blank=True, null=True)),
                ('not_follow_rule_per', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'safety_rule',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='CountryData',
        ),
        migrations.DeleteModel(
            name='PriceperMin',
        ),
    ]
